repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks: [{id: black}]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks: [{id: isort}]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks: [{id: flake8, args: [--max-line-length=88]}]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks: [{id: golangci-lint}]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks: [{id: trailing-whitespace}, {id: end-of-file-fixer}]
